# Force exact Node version & install dev deps (Vite, plugins)
[variables]
NIXPACKS_NODE_VERSION = "18"
NPM_CONFIG_PRODUCTION = "false"
# Or: NIXPACKS_INSTALL_DEV = "1"

# Explicit phases so Nixpacks doesn't get clever
[phases.install]
cmds = ["npm i"]

[phases.build]
cmds = ["npm run build"]

[start]
# Use your package.json start cmd (serve -s dist -l $PORT --single)
cmd = "npm run start"
