export const FORMATIONS = {
  "4-3-3": [
    { key: "GK", pos: "GK",  x: 6,  y: 50 },
    { key: "LB", pos: "LB",  x: 20, y: 22 },
    { key: "LCB", pos: "LCB", x: 23, y: 45 },
    { key: "RCB", pos: "RCB", x: 23, y: 55 },
    { key: "RB", pos: "RB",  x: 20, y: 78 },
    { key: "CM1", pos: "CM", x: 45, y: 30 },
    { key: "CM2", pos: "CM", x: 45, y: 70 },
    { key: "CM3", pos: "CM", x: 48, y: 50 },
    { key: "LW", pos: "LW",  x: 70, y: 22 },
    { key: "ST", pos: "ST",  x: 76, y: 50 },
    { key: "RW", pos: "RW",  x: 70, y: 78 },
  ],
  "4-1-2-1-2": [
    { key: "GK", pos: "GK",  x: 6,  y: 50 },
    { key: "LB", pos: "LB",  x: 20, y: 22 },
    { key: "LCB", pos: "LCB", x: 23, y: 45 },
    { key: "RCB", pos: "RCB", x: 23, y: 55 },
    { key: "RB", pos: "RB",  x: 20, y: 78 },
    { key: "CDM", pos: "CDM", x: 40, y: 50 },
    { key: "LM", pos: "LM",  x: 57, y: 28 },
    { key: "RM", pos: "RM",  x: 57, y: 72 },
    { key: "CAM", pos: "CAM",x: 66, y: 50 },
    { key: "ST1", pos: "ST", x: 81, y: 40 },
    { key: "ST2", pos: "ST", x: 81, y: 60 },
  ],
  "4-4-2": [
    { key: "GK", pos: "GK",  x: 6,  y: 50 },
    { key: "LB", pos: "LB",  x: 20, y: 22 },
    { key: "LCB", pos: "LCB", x: 23, y: 45 },
    { key: "RCB", pos: "RCB", x: 23, y: 55 },
    { key: "RB", pos: "RB",  x: 20, y: 78 },
    { key: "LM", pos: "LM",  x: 51, y: 28 },
    { key: "CM1", pos: "CM", x: 48, y: 45 },
    { key: "CM2", pos: "CM", x: 48, y: 55 },
    { key: "RM", pos: "RM",  x: 51, y: 72 },
    { key: "ST1", pos: "ST", x: 79, y: 42 },
    { key: "ST2", pos: "ST", x: 79, y: 58 },
  ],
};
